### ISSUE TITLE
googletagmanager 这段 js 执行太慢

### ISSUE THREAD

**Issue by UXplayer** [Anyway-Design/Anyway.ABC#2]
现象：
打开网页后，点击播放音频听不到声音
等了几分钟再切回来，音频又能正常播放了

原因：
![image](https://user-images.githubusercontent.com/16333847/39359209-9ef4f06a-4a4b-11e8-8ce8-4d24ef54ee4a.png)
查到是由于 googletagmanager 这段 js 执行过慢，在它执行完或超时之前，语音都无法正常播放。
也许是我翻墙环境还不够好导致的（我看 1080p YouTube 时会有点卡）。

**Comment by JJYing** [comment]
彻底去掉了 GA 代码
